language: objective-c
osx_image: xcode8.3
xcode_project: JLDemo.xcodeproj
xcode_scheme: JLDemoTests
script:
  - xcodebuild clean build test -project JLDemo.xcodeproj -scheme JLDemoTests -destination 'platform=iOS Simulator,name=iPad Air,OS=10.0'
after_success:
  - bash <(curl -s https://codecov.io/bash)
